/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.purchaseandsalesrecordgui.controller;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import ec.edu.espe.filemanagerlibrary.FileManager;
import ec.edu.espe.purchaseandsalesrecordgui.model.Customer;
import ec.edu.espe.purchaseandsalesrecordgui.model.Clothing;
<<<<<<< HEAD
import ec.edu.espe.purchaseandsalesrecordgui.utils.Calculation;
=======
import ec.edu.espe.purchaseandsalesrecordgui.utils.ValidationEmptyFields;
>>>>>>> 974ea7173140254f80c652ddb1f087325f1fecda
import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Jhonatan Lituma
 */
public class FrmCreateInvoice extends javax.swing.JFrame {

<<<<<<< HEAD
    DB db;
    DBCollection invoices;

    String filePathClients = "data/clients.json";
=======
    String filePathCustomers = "data/customer.json";
>>>>>>> 974ea7173140254f80c652ddb1f087325f1fecda
    String filePathInvoices = "data/invoices.json";
    String filePathClothing = "data/clothing.json";
    String filePathSizeOfClothing = "data/sizeOfClothing.json";
    String filePathAccounting = "data/accounting.json";
    private DefaultComboBoxModel<Customer> model = new DefaultComboBoxModel<>();
    private DefaultComboBoxModel modelClothing = new DefaultComboBoxModel();
    private DefaultComboBoxModel modelSize = new DefaultComboBoxModel();
    private DefaultComboBoxModel modelQuantity = new DefaultComboBoxModel();
    private DefaultTableModel modelTable = new DefaultTableModel();

    /**
     * Creates new form Aplication
     * @throws java.net.UnknownHostException
     */
    public FrmCreateInvoice() throws UnknownHostException {
        try {
            Mongo mongoDb = new Mongo("localhost", 27017);
            db = mongoDb.getDB("DataBaseStore");//Base de datos
            invoices = db.getCollection("Invoices");//Coleccion
        } catch (UnknownHostException ex) {
            Logger.getLogger(FrmCreateInvoice.class.getName()).log(Level.SEVERE, null, ex);
        }

        completeModelComboBoxClients();
        completeModelComboBoxClothing();

        initComponents();
        setLocationRelativeTo(null);
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/YYYY");
        txtDate.setEditable(false);
        txtDate.setText(simpleDateFormat.format(date));
        txtQuantity.setText("0");
        txtTotal.setText("0.0");
    }

    private void completeModelComboBoxClients() {
        ArrayList<Customer> customers = new ArrayList<>();
        Gson gson = new Gson();
        String json = "";
        try {
            json = FileManager.read(filePathCustomers);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "File not found, we are creating the file.");
        }
        //System.out.println(json);
        java.lang.reflect.Type customerType = new TypeToken<ArrayList<Customer>>() {
        }.getType();
        customers = gson.fromJson(json, customerType);

        for (Customer customer : customers) {
            model.addElement(customer);
        }
    }

    private void completeModelComboBoxClothing() {
        ArrayList<Clothing> clothes = new ArrayList<>();
        Gson gson = new Gson();
        String json = "";
        try {
            json = FileManager.read(filePathClothing);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "File not found, we are creating the file.");
        }
        java.lang.reflect.Type clothingType = new TypeToken<ArrayList<Clothing>>() {
        }.getType();
        clothes = gson.fromJson(json, clothingType);

        for (Clothing clothing : clothes) {
            modelClothing.addElement(clothing);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbPersons = new javax.swing.JComboBox<>();
        btnShowData = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCellphone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        cmbClothing = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbSizeOfClothing = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        jlbOnlyNumbersCedula = new javax.swing.JLabel();
        jlbOnlyNumbersCellphone = new javax.swing.JLabel();
        jlbValidateEmail = new javax.swing.JLabel();
        jlbOnlyNumbersTax = new javax.swing.JLabel();
        jlbOnlyNumbersQuantity = new javax.swing.JLabel();
        jlbOnlyNumbersId = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invoice Managment");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/purchaseandsalesrecordgui/images/persona_opt.png"))); // NOI18N
        jLabel1.setText("Cedula:");

        cmbPersons.setModel(model);

        btnShowData.setText("Show Data");
        btnShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDataActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name:");

        jLabel5.setText("Cedula:");

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
        });

        jLabel6.setText("Cellphone: ");

        txtCellphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCellphoneKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Date of the Invoice:");

        jLabel3.setText("Name:");

        jLabel10.setText("Address:");

        jLabel12.setText("Email:");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(txtAddress))
                        .addGap(46, 46, 46)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCellphone, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(txtCedula))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCellphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Products to buy:");

        labelID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelID.setText("Invoice ID:");

        labelDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelDate.setText("Date:");

        jLabel13.setText("Tax:");

        txtTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTaxKeyPressed(evt);
            }
        });

        jLabel14.setText("Total:");

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });

        cmbClothing.setModel(modelClothing);
        cmbClothing.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClothingItemStateChanged(evt);
            }
        });

        jLabel15.setText("Clothing");

        jLabel7.setText("Size");

        cmbSizeOfClothing.setModel(modelSize);

        jLabel8.setText("Quantity");

        btnTotal.setText("Add to the total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
        });

        jlbOnlyNumbersCedula.setForeground(new java.awt.Color(255, 0, 0));

        jlbOnlyNumbersCellphone.setForeground(new java.awt.Color(255, 0, 0));

        jlbValidateEmail.setForeground(new java.awt.Color(255, 0, 0));

        jlbOnlyNumbersTax.setForeground(new java.awt.Color(255, 0, 0));

        jlbOnlyNumbersQuantity.setForeground(new java.awt.Color(255, 0, 0));

        jlbOnlyNumbersId.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbOnlyNumbersId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowData, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDate)))
                        .addGap(48, 48, 48)))
                .addGap(0, 122, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbOnlyNumbersCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbOnlyNumbersCellphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbValidateEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlbOnlyNumbersTax, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addGap(130, 130, 130)))
                                .addComponent(btnReturn)
                                .addGap(93, 93, 93))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(112, 338, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbClothing, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSizeOfClothing, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTotal)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbOnlyNumbersQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(labelDate)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbOnlyNumbersId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jlbOnlyNumbersCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbOnlyNumbersCellphone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValidateEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmbClothing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmbSizeOfClothing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbOnlyNumbersQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbOnlyNumbersTax, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnReturn)
                    .addComponent(btnTotal))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDataActionPerformed
        // TODO add your handling code here:
        ArrayList<Customer> clients = new ArrayList<>();
        Gson gson = new Gson();
        String json = "";

        try {
<<<<<<< HEAD
            json = FileManager.read(filePathClients);
       } catch (IOException e) {
=======
            json = FileManager.read(filePathCustomers);
        } catch (IOException e) {
>>>>>>> 974ea7173140254f80c652ddb1f087325f1fecda
            JOptionPane.showMessageDialog(null, "Something is wrong, an unexpected error has occurred, try again.");
        }

        Customer customer = (Customer) model.getSelectedItem();

        String cedula = Integer.toString(customer.getCedula());
        String cellphone = Integer.toString(customer.getCellphone());

        java.lang.reflect.Type customerType = new TypeToken<ArrayList<Customer>>() {
        }.getType();
        clients = gson.fromJson(json, customerType);
        txtName.setText(customer.getName());
        txtName.setEditable(false);
        txtLastName.setText(customer.getLastName());
        txtLastName.setEditable(false);
        txtCedula.setText(cedula);
        txtCedula.setEditable(false);
        txtCellphone.setText(cellphone);
        txtCellphone.setEditable(false);
        txtAddress.setText(customer.getAddress());
        txtAddress.setEditable(false);
        txtEmail.setText(customer.getEmail());
        txtEmail.setEditable(false);

    }//GEN-LAST:event_btnShowDataActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        FrmInvoiceManagement frmInvoices = new FrmInvoiceManagement();
        frmInvoices.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
        BasicDBObject basicDBObject = new BasicDBObject();       
        
        basicDBObject.put("idInvoice", txtId.getText());
        basicDBObject.put("date", txtDate.getText());
        basicDBObject.put("cedula", txtCedula.getText());
        basicDBObject.put("name", txtName.getText());
        basicDBObject.put("lastName", txtLastName.getText());
        basicDBObject.put("address", txtAddress.getText());
        basicDBObject.put("cellphone", txtCellphone.getText());
        basicDBObject.put("email", txtEmail.getText());
        basicDBObject.put("clothing", String.valueOf(cmbClothing.getSelectedItem()));
        basicDBObject.put("descrption", cmbSizeOfClothing.getSelectedItem());
        basicDBObject.put("quantity", txtQuantity.getText());
        basicDBObject.put("tax", txtTax.getText());
        basicDBObject.put("total", txtTotal.getText());
        
        int saveOption = JOptionPane.showConfirmDialog(rootPane, "Are you sure to print this information.?");
        if (saveOption == 0) {
            invoices.insert(basicDBObject);
            JOptionPane.showMessageDialog(rootPane, "Saved!");
        } else if (saveOption == 1) {
            JOptionPane.showMessageDialog(rootPane, "Ok, try again.");
=======
        JSONObject jsonObject = new JSONObject();
        JSONArray jsonArray = new JSONArray();
        JSONParser jsonParser = new JSONParser();
        JSONObject jsonObjectAccounting = new JSONObject();
        JSONArray jsonArrayAccounting = new JSONArray();
        JSONParser jsonParserAccounting = new JSONParser();
        ValidationEmptyFields validation = new ValidationEmptyFields();

        try {
            jsonArray = (JSONArray) jsonParser.parse(FileManager.readRecord(filePathInvoices));
        } catch (IOException | ParseException ex) {
            JOptionPane.showMessageDialog(null, "Something is wrong, an unexpected error has occurred, try again.");
        }

        jsonObject.put("idInvoice", txtId.getText());
        jsonObject.put("date", txtDate.getText());
        jsonObject.put("cedula", txtCedula.getText());
        jsonObject.put("name", txtName.getText());
        jsonObject.put("lastName", txtLastName.getText());
        jsonObject.put("address", txtAddress.getText());
        jsonObject.put("cellphone", txtCellphone.getText());
        jsonObject.put("email", txtEmail.getText());
        jsonObject.put("clothing", String.valueOf(cmbClothing.getSelectedItem()));
        jsonObject.put("descrption", cmbSizeOfClothing.getSelectedItem());
        jsonObject.put("quantity", txtQuantity.getText());
        jsonObject.put("tax", txtTax.getText());
        jsonObject.put("total", txtTotal.getText());
        jsonArray.add(jsonObject);

        String cedula = txtCedula.getText();
        String email = txtEmail.getText();

        if (validation.validateCedula(cedula) == true) {
            if (validation.validateEmail(email) == true) {

                int saveOption = JOptionPane.showConfirmDialog(rootPane, "Are you sure to print this information.?");
                if (saveOption == 0) {
                    try {
                        int id = Integer.parseInt(txtId.getText());
                        id++;
                        String idAsString = Integer.toString(id);
                        txtId.setText(idAsString);
                        FileManager.writeRecord(filePathInvoices, jsonArray.toJSONString());
                        JOptionPane.showMessageDialog(rootPane, "Saved!");
                        jlbOnlyNumbersCedula.setText("");
                        jlbOnlyNumbersCellphone.setText("");
                        jlbValidateEmail.setText("");
                        jlbOnlyNumbersTax.setText("");
                        jlbOnlyNumbersQuantity.setText("");
                        jlbOnlyNumbersId.setText("");
                    } catch (HeadlessException | IOException | NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Something is wrong, an unexpected error has occurred, try again.");
                    }

                } else if (saveOption == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Ok, try again.");
                }
            } else {
                jlbValidateEmail.setText("Invalid Email!");
                JOptionPane.showMessageDialog(null, "Invalid Email!");
            }
        } else {
            jlbOnlyNumbersCedula.setText("Invalid Cedula!");
            JOptionPane.showMessageDialog(null, "Invalid Cedula!");
        }

        try {
            jsonArrayAccounting = (JSONArray) jsonParserAccounting.parse(FileManager.readRecord(filePathAccounting));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "File not found, we are creating the file.");
        }

        jsonObjectAccounting.put("date", txtDate.getText());
        jsonObjectAccounting.put("clothing", String.valueOf(cmbClothing.getSelectedItem()));
        jsonObjectAccounting.put("income", txtTotal.getText());
        jsonObjectAccounting.put("descrption", cmbSizeOfClothing.getSelectedItem());

        jsonArrayAccounting.add(jsonObjectAccounting);

        try {
            FileManager.writeRecord(filePathAccounting, jsonArrayAccounting.toJSONString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "File not found, we are creating the file.");
>>>>>>> 974ea7173140254f80c652ddb1f087325f1fecda
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed

        JSONObject jsonOldObject = new JSONObject();
        JSONArray jsonArray = new JSONArray();
        JSONParser jsonParser = new JSONParser();
        double tax;
        double pricePerUnit;
        double totalWithoutIva = 0;
        double totalWithIva = Double.parseDouble(txtTotal.getText());
        double quantity;
        long totalQuantity = Long.parseLong(txtQuantity.getText());
        Calculation calculation = new Calculation();
                
        try {
            jsonArray = (JSONArray) jsonParser.parse(FileManager.readRecord(filePathClothing));
        } catch (IOException | ParseException e) {
            JOptionPane.showMessageDialog(null, "File not found, we are creating the file.");
        }

        Clothing clothing = (Clothing) modelClothing.getSelectedItem();
        long quantityOfClothing = Long.valueOf(txtQuantity.getText());

        jsonOldObject = (JSONObject) jsonArray.get(cmbClothing.getSelectedIndex());

        if (jsonOldObject.get("id").equals(clothing.getId()) && jsonOldObject.get("typeOfClothing").equals(clothing.getTypeOfClothing()) && jsonOldObject.get("size").equals(clothing.getSize()) && jsonOldObject.get("idProvider").equals(clothing.getIdProvider()) && jsonOldObject.get("brand").equals(clothing.getBrand()) && quantityOfClothing > Long.parseLong(String.valueOf(jsonOldObject.get("quantity")))) {
            JOptionPane.showMessageDialog(null, "Exceeds the quantity available.");
        } else {
            tax = Integer.parseInt(txtTax.getText());
            pricePerUnit = clothing.getSalePrice();
            quantity = Double.parseDouble(txtQuantity.getText());
            
            totalWithoutIva = calculation.PriceWithOutIva(quantity, pricePerUnit);
            totalWithIva = calculation.PriceWithIva(tax, totalWithoutIva);
            
            txtTotal.setText(String.valueOf(totalWithIva));

            long currentlyQuantity = Long.parseLong((String.valueOf(jsonOldObject.get("quantity"))));
            currentlyQuantity -= totalQuantity;
            jsonOldObject.put("quantity", currentlyQuantity);
            jsonArray.remove(cmbClothing.getSelectedIndex());

            jsonArray.add(cmbClothing.getSelectedIndex(), jsonOldObject);
            try {
                FileManager.writeRecord(filePathClothing, jsonArray.toJSONString());
            } catch (HeadlessException | IOException ex) {
                JOptionPane.showMessageDialog(null, "Something is wrong, an unexpected error has occurred, try again.");
            }
        }


    }//GEN-LAST:event_btnTotalActionPerformed

    private void cmbClothingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClothingItemStateChanged
        // TODO add your handling code here
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Clothing clothing = (Clothing) modelClothing.getSelectedItem();
            modelSize.setSelectedItem(clothing.getSize());

        }
    }//GEN-LAST:event_cmbClothingItemStateChanged

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed
        ValidationEmptyFields validation = new ValidationEmptyFields();
        validation.validateOnlyNumbers(evt, txtCedula, jlbOnlyNumbersCedula);
    }//GEN-LAST:event_txtCedulaKeyPressed

    private void txtCellphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCellphoneKeyPressed
        ValidationEmptyFields validation = new ValidationEmptyFields();
        validation.validateOnlyNumbers(evt, txtCellphone, jlbOnlyNumbersCellphone);
    }//GEN-LAST:event_txtCellphoneKeyPressed

    private void txtTaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaxKeyPressed
        ValidationEmptyFields validation = new ValidationEmptyFields();
        validation.validateOnlyNumbers(evt, txtTax, jlbOnlyNumbersTax);
    }//GEN-LAST:event_txtTaxKeyPressed

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        ValidationEmptyFields validation = new ValidationEmptyFields();
        validation.validateOnlyNumbers(evt, txtQuantity, jlbOnlyNumbersQuantity);
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        ValidationEmptyFields validation = new ValidationEmptyFields();
        validation.validateOnlyNumbers(evt, txtId, jlbOnlyNumbersId);
    }//GEN-LAST:event_txtIdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new FrmCreateInvoice().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(FrmCreateInvoice.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowData;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cmbClothing;
    private javax.swing.JComboBox<ec.edu.espe.purchaseandsalesrecordgui.model.Customer> cmbPersons;
    private javax.swing.JComboBox<String> cmbSizeOfClothing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlbOnlyNumbersCedula;
    private javax.swing.JLabel jlbOnlyNumbersCellphone;
    private javax.swing.JLabel jlbOnlyNumbersId;
    private javax.swing.JLabel jlbOnlyNumbersQuantity;
    private javax.swing.JLabel jlbOnlyNumbersTax;
    private javax.swing.JLabel jlbValidateEmail;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelID;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCellphone;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
